---
- name: Ensure tag {{ tag.name }} is {{ tag.state | default('present') }} in vCenter
  community.vmware.vmware_tag:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"
    category_id: "{{ category_rst.category_results.category_id }}"
    tag_name: "{{ tag.name }}"
    tag_description: "{{ tag.description }}"
    state: "{{ tag.state | default('present') }}"
  delegate_to: localhost
